spring.application.name=auth-service
server.port=8081

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.enabled=true

# PostgreSQL (Single DB, user/password: postgres/root)
spring.datasource.url=jdbc:postgresql://localhost:5432/colegio_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=colegio-sistema-escolar-jwt-secret-key-2024-muy-larga-para-seguridad
app.jwt.expiration-ms=86400000

# Default password for new users
app.security.default-password=Colegio2024

# Kafka (Con tolerancia a fallos para desarrollo local)
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.properties.max.block.ms=3000
spring.kafka.properties.request.timeout.ms=3000
spring.kafka.properties.delivery.timeout.ms=3000


# Optimización de conexiones (base de datos única)
spring.datasource.hikari.maximum-pool-size=2
