spring.application.name=eureka-server
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false


# Optimización de conexiones (base de datos única)
spring.datasource.hikari.maximum-pool-size=2
