server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**

        - id: audit-service
          uri: lb://AUDIT-SERVICE
          predicates:
            - Path=/api/audit/**

        - id: recovery-service
          uri: lb://RECOVERY-SERVICE
          predicates:
            - Path=/api/recovery/**

        - id: course-service
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/api/v1/courses/**

        - id: section-service
          uri: lb://SECTION-SERVICE
          predicates:
            - Path=/api/v1/sections/**

        - id: enrollment-service
          uri: lb://ENROLLMENT-SERVICE
          predicates:
            - Path=/api/enrollment/**

# Configuración de Cliente Eureka
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Logging para depuración del ruteo reactivo
logging:
  level:
    org.springframework.cloud.gateway: INFO
