spring.application.name=config-server

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.enabled=true

# Database Configuration (Configured for consistency across services)
spring.datasource.url=jdbc:postgresql://localhost:5432/colegio_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver


# Optimización de conexiones (base de datos única)
spring.datasource.hikari.maximum-pool-size=2
